CREATE TABLE REGISTER(NAME TEXT NOT NULL, EMAIL TEXT NOT NULL, COLLEGE TEXT NOT NULL, CHOICE TEXT NOT NULL, TEAM TEXT NOT NULL , CONTACT TEXT NOT NULL, VOLUNTEER TEXT NOT NULL);
CREATE TABLE VOLUNTEERS(NAME TEXT,PASSWORD TEXT ,JOB TEXT ,CONTACT TEXT);
